// dashboard/react-scenario/src/components/Sidebar.jsx
import { NavLink } from 'react-router-dom'
import { useTheme } from '../context/ThemeContext'
import styles from '../css/Layout.module.css'

const links = [
  { to: '/', label: 'Overview', icon: '📊' },
  { to: '/products', label: 'Products', icon: '📦' },
  { to: '/orders', label: 'Orders', icon: '🛒' },
  { to: '/settings', label: 'Settings', icon: '⚙️' },
]

export default function Sidebar() {
  const { darkMode } = useTheme()

  return (
    <aside className={styles.sidebar} style={{
      backgroundColor: darkMode ? '#111827' : '#ffffff',
      color: darkMode ? '#ffffff' : '#1f2937',
    }}>
      <h1 className={styles.sidebarTitle}>🛍️ ShopDash</h1>
      <nav className={styles.nav}>
        {links.map(link => (
          <NavLink
            key={link.to}
            to={link.to}
            end
            className={styles.navLink}
            style={({ isActive }) => ({
              backgroundColor: isActive ? '#2563eb' : 'transparent',
              color: isActive ? '#ffffff' : darkMode ? '#ffffff' : '#1f2937',
            })}
          >
            <span>{link.icon}</span>
            <span>{link.label}</span>
          </NavLink>
        ))}
      </nav>
    </aside>
  )
}

// dashboard/vue-scenario/src/components/Sidebar.vue
<template>
  <aside :class="styles.sidebar" :style="{
    backgroundColor: darkMode ? '#111827' : '#ffffff',
    color: darkMode ? '#ffffff' : '#1f2937',
  }">
    <h1 :class="styles.sidebarTitle">🛍️ ShopDash</h1>
    <nav :class="styles.nav">
      <router-link
        v-for="link in links"
        :key="link.to"
        :to="link.to"
        custom
        v-slot="{ isActive, navigate }"
      >
        <div
          @click="navigate"
          :class="styles.navLink"
          :style="{
            backgroundColor: isActive ? '#2563eb' : 'transparent',
            color: isActive ? '#ffffff' : darkMode ? '#ffffff' : '#1f2937',
            cursor: 'pointer',
          }"
        >
          <span>{{ link.icon }}</span>
          <span>{{ link.label }}</span>
        </div>
      </router-link>
    </nav>
  </aside>
</template>

<script setup>
import { useCssModule } from 'vue'
import { useTheme } from '../context/useTheme'

const styles = useCssModule()
const { darkMode } = useTheme()

const links = [
  { to: '/', label: 'Overview', icon: '📊' },
  { to: '/products', label: 'Products', icon: '📦' },
  { to: '/orders', label: 'Orders', icon: '🛒' },
  { to: '/settings', label: 'Settings', icon: '⚙️' },
]
</script>

<style module src="../css/Layout.module.css"></style>
