// vue-scenario/src/components/navbar.vue
<script setup>
import { ref } from 'vue'
import styles from '../css/Navbar.module.css'
const isOpen = ref(false)

const toggleSidebar = () => {
  isOpen.value = !isOpen.value
}
</script> 

<template>
  <div>
    <button :class="styles.hamburger" @click="toggleSidebar">
      &#9776;
    </button>
    
    <nav :class="[styles.sidebar, { [styles.open]: isOpen }]">
      <button :class="styles.closeBtn" @click="toggleSidebar">
        &times;
      </button>
      
      <router-link to="/" @click="toggleSidebar" :class="styles.link">
        Home
      </router-link>
      
      <router-link to="/photography" @click="toggleSidebar" :class="styles.link">
        Photography
      </router-link>

      <router-link to="/videography" @click="toggleSidebar" :class="styles.link">
        Videography
      </router-link>

      <router-link to="/enquiries" @click="toggleSidebar" :class="styles.link">
        Enquiries
      </router-link>
      
    </nav>
  </div>
</template>

// react-scenario/src/components/Navbar.jsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import styles from './Navbar.module.css';

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      <button className={styles.hamburger} onClick={toggleSidebar}>
        &#9776;
      </button>
      <nav className={`${styles.sidebar} ${isOpen ? styles.open : ''}`}>
        <button className={styles.closeBtn} onClick={toggleSidebar}>
          &times;
        </button>
        <Link to="/" onClick={toggleSidebar} className={styles.link}>
          Home
        </Link>
        <Link to="/photography" onClick={toggleSidebar} className={styles.link}>
          Photography
        </Link>
        <Link to="/videography" onClick={toggleSidebar} className={styles.link}>
          Videography
        </Link>
        <Link to="/enquiries" onClick={toggleSidebar} className={styles.link}>
          Enquiries
        </Link>
      </nav>
    </>
  );
};

export default Navbar;
