// react-scenario/src/pages/MediaGallery.jsx
// src/pages/MediaGallery.jsx
// Main media gallery page that combines all components

import React, { useState, useEffect } from 'react';
import { fetchMediaItems, uploadFile } from '../services/mediaApi';
import UploadZone from '../components/UploadZone';
import CategoryFilter from '../components/CategoryFilter';
import MediaCard from '../components/MediaCard';
import MediaLightbox from '../components/MediaLightbox';

const MediaGallery = () => {
  const [mediaItems, setMediaItems] = useState([]);
  const [isUploading, setIsUploading] = useState(false);
  const [activeCategory, setActiveCategory] = useState('all');
  const [lightboxIndex, setLightboxIndex] = useState(null);

  // Fetch media on component mount
  useEffect(() => {
    loadMedia();
  }, []);

  const loadMedia = async () => {
    try {
      const items = await fetchMediaItems();
      setMediaItems(items);
    } catch (error) {
      console.error('Failed to load media:', error);
    }
  };

  const handleUpload = async (event) => {
    const files = Array.from(event.target.files);
    if (files.length === 0) return;

    setIsUploading(true);

    for (const file of files) {
      try {
        await uploadFile(file);
      } catch (error) {
        console.error('Upload failed:', error);
      }
    }

    setIsUploading(false);
    loadMedia(); // Refresh media list
  };

  // Filter media by category
  const filteredMedia = activeCategory === 'all' 
    ? mediaItems 
    : mediaItems.filter(item => item.category === activeCategory);

  // Lightbox navigation
  const openLightbox = (index) => setLightboxIndex(index);
  const closeLightbox = () => setLightboxIndex(null);
  const nextMedia = () => setLightboxIndex((lightboxIndex + 1) % filteredMedia.length);
  const prevMedia = () => setLightboxIndex((lightboxIndex - 1 + filteredMedia.length) % filteredMedia.length);

  return (
    <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '40px' }}>
      {/* Upload Section */}
      <div className="stagger-3">
        <UploadZone onUpload={handleUpload} isUploading={isUploading} />
      </div>

      {/* Category Filters */}
      <div className="stagger-4">
        <CategoryFilter 
          activeCategory={activeCategory} 
          onCategoryChange={setActiveCategory} 
        />
      </div>

      {/* Media Grid */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
        gap: '24px',
        marginTop: '40px'
      }}>
        {filteredMedia.map((item, index) => (
          <MediaCard
            key={item.id}
            item={item}
            index={index}
            onClick={() => openLightbox(index)}
          />
        ))}
      </div>

      {/* Empty State */}
      {filteredMedia.length === 0 && (
        <div style={{
          textAlign: 'center',
          padding: '80px 20px',
          color: 'rgba(224, 224, 224, 0.4)'
        }}>
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>∅</div>
          <div style={{ fontSize: '18px', letterSpacing: '2px' }}>
            NO MEDIA FOUND
          </div>
          <div style={{ fontSize: '14px', marginTop: '8px', opacity: 0.6 }}>
            Upload some images or videos to get started
          </div>
        </div>
      )}

      {/* Lightbox */}
      <MediaLightbox
        media={filteredMedia}
        currentIndex={lightboxIndex}
        onClose={closeLightbox}
        onNext={nextMedia}
        onPrev={prevMedia}
      />
    </div>
  );
};

export default MediaGallery;

// portfolio/vue-scenario/src/pages/MediaGallery.vue
<!-- src/pages/MediaGallery.vue -->
<!-- Main media gallery page that combines all components -->
<template>
  <div class="media-gallery">
    <!-- Upload Section -->
    <div class="stagger-3">
      <UploadZone 
        :is-uploading="isUploading" 
        @upload="handleUpload" 
      />
    </div>

    <!-- Category Filters -->
    <div class="stagger-4">
      <CategoryFilter v-model="activeCategory" />
    </div>

    <!-- Media Grid -->
    <div class="media-grid">
      <MediaCard
        v-for="(item, index) in filteredMedia"
        :key="item.id"
        :item="item"
        :index="index"
        @click="openLightbox(index)"
      />
    </div>

    <!-- Empty State -->
    <div v-if="filteredMedia.length === 0" class="empty-state">
      <div class="empty-icon">∅</div>
      <div class="empty-title">NO MEDIA FOUND</div>
      <div class="empty-subtitle">Upload some images or videos to get started</div>
    </div>

    <!-- Lightbox -->
    <MediaLightbox
      :media="filteredMedia"
      :current-index="lightboxIndex"
      @close="closeLightbox"
      @next="nextMedia"
      @prev="prevMedia"
    />
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { fetchMediaItems, uploadFile } from '../services/mediaApi';
import UploadZone from '../components/UploadZone.vue';
import CategoryFilter from '../components/CategoryFilter.vue';
import MediaCard from '../components/MediaCard.vue';
import MediaLightbox from '../components/MediaLightbox.vue';

const mediaItems = ref([]);
const isUploading = ref(false);
const activeCategory = ref('all');
const lightboxIndex = ref(null);

// Fetch media on component mount
onMounted(async () => {
  await loadMedia();
});

const loadMedia = async () => {
  try {
    const items = await fetchMediaItems();
    mediaItems.value = items;
  } catch (error) {
    console.error('Failed to load media:', error);
  }
};

const handleUpload = async (event) => {
  const files = Array.from(event.target.files);
  if (files.length === 0) return;

  isUploading.value = true;

  for (const file of files) {
    try {
      await uploadFile(file);
    } catch (error) {
      console.error('Upload failed:', error);
    }
  }

  isUploading.value = false;
  await loadMedia(); // Refresh media list
};

// Filter media by category
const filteredMedia = computed(() => {
  if (activeCategory.value === 'all') {
    return mediaItems.value;
  }
  return mediaItems.value.filter(item => item.category === activeCategory.value);
});

// Lightbox navigation
const openLightbox = (index) => {
  lightboxIndex.value = index;
};

const closeLightbox = () => {
  lightboxIndex.value = null;
};

const nextMedia = () => {
  lightboxIndex.value = (lightboxIndex.value + 1) % filteredMedia.value.length;
};

const prevMedia = () => {
  lightboxIndex.value = (lightboxIndex.value - 1 + filteredMedia.value.length) % filteredMedia.value.length;
};
</script>

<style scoped>
.media-gallery {
  max-width: 1400px;
  margin: 0 auto;
  padding: 40px;
}

.media-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 24px;
  margin-top: 40px;
}

.empty-state {
  text-align: center;
  padding: 80px 20px;
  color: rgba(224, 224, 224, 0.4);
}

.empty-icon {
  font-size: 48px;
  margin-bottom: 16px;
}

.empty-title {
  font-size: 18px;
  letter-spacing: 2px;
}

.empty-subtitle {
  font-size: 14px;
  margin-top: 8px;
  opacity: 0.6;
}

.stagger-3 { animation: fadeInUp 0.6s ease-out 0.3s backwards; }
.stagger-4 { animation: fadeInUp 0.6s ease-out 0.4s backwards; }

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
