// dashboard/react-scenario/src/pages/Overview.jsx
import { useTheme } from '../context/ThemeContext'
import { products, orders, revenueData } from '../data/mockData'
import styles from '../css/global.module.css'
import {
  LineChart, Line, BarChart, Bar,
  XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer
} from 'recharts'

const totalRevenue = orders.reduce((sum, o) => sum + o.total, 0)

const kpis = [
  { label: 'Total Revenue', value: `£${totalRevenue.toFixed(2)}`, icon: '💰', color: '#2563eb' },
  { label: 'Total Orders', value: orders.length, icon: '🛒', color: '#16a34a' },
  { label: 'Total Products', value: products.length, icon: '📦', color: '#9333ea' },
  { label: 'Low Stock Items', value: products.filter(p => p.stock < 50).length, icon: '⚠️', color: '#dc2626' },
]

export default function Overview() {
  const { darkMode } = useTheme()

  const cardBg = { backgroundColor: darkMode ? '#1f2937' : '#ffffff' }
  const mutedText = { color: darkMode ? '#9ca3af' : '#6b7280' }
  const gridStroke = darkMode ? '#374151' : '#e5e7eb'
  const axisStroke = darkMode ? '#9ca3af' : '#6b7280'
  const tooltipBg = { backgroundColor: darkMode ? '#1f2937' : '#fff' }

  return (
    <div className={styles.page}>
      <h1 className={styles.pageTitle}>Overview</h1>

      {/* KPI Cards */}
      <div className={styles.grid4}>
        {kpis.map(kpi => (
          <div key={kpi.label} className={styles.card} style={cardBg}>
            <div className={styles.flexBetween}>
              <div>
                <p style={{ fontSize: '14px', ...mutedText }}>{kpi.label}</p>
                <p style={{ fontSize: '28px', fontWeight: 'bold', color: kpi.color }}>{kpi.value}</p>
              </div>
              <span style={{ fontSize: '32px' }}>{kpi.icon}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Charts */}
      <div className={styles.grid2}>
        <div className={styles.card} style={cardBg}>
          <h2 className={styles.cardTitle}>Monthly Revenue</h2>
          <ResponsiveContainer width="100%" height={250}>
            <LineChart data={revenueData}>
              <CartesianGrid strokeDasharray="3 3" stroke={gridStroke} />
              <XAxis dataKey="month" stroke={axisStroke} />
              <YAxis stroke={axisStroke} />
              <Tooltip contentStyle={tooltipBg} />
              <Line type="monotone" dataKey="revenue" stroke="#2563eb" strokeWidth={2} dot={{ r: 4 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        <div className={styles.card} style={cardBg}>
          <h2 className={styles.cardTitle}>Revenue by Month</h2>
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={revenueData}>
              <CartesianGrid strokeDasharray="3 3" stroke={gridStroke} />
              <XAxis dataKey="month" stroke={axisStroke} />
              <YAxis stroke={axisStroke} />
              <Tooltip contentStyle={tooltipBg} />
              <Bar dataKey="revenue" fill="#2563eb" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  )
}

// dashboard/vue-scenario/src/pages/Overview.vue
<template>
  <div :class="styles.page">
    <h1 :class="styles.pageTitle">Overview</h1>

    <!-- KPI Cards -->
    <div :class="styles.grid4">
      <div v-for="kpi in kpis" :key="kpi.label" :class="styles.card" :style="cardBg">
        <div :class="styles.flexBetween">
          <div>
            <p :style="{ fontSize: '14px', color: darkMode ? '#9ca3af' : '#6b7280' }">{{ kpi.label }}</p>
            <p :style="{ fontSize: '28px', fontWeight: 'bold', color: kpi.color }">{{ kpi.value }}</p>
          </div>
          <span style="font-size: 32px;">{{ kpi.icon }}</span>
        </div>
      </div>
    </div>

    <!-- Charts -->
    <div :class="styles.grid2">
      <div :class="styles.card" :style="cardBg">
        <h2 :class="styles.cardTitle">Monthly Revenue</h2>
        <LineChart :data="revenueData" :darkMode="darkMode" />
        <div style="height: 300px;">
          <Line :data="chartData" :options="chartOptions" />
        </div>
      </div>
      <div :class="styles.card" :style="cardBg">
        <h2 :class="styles.cardTitle">Revenue by Month</h2>
        <div style="height: 300px;">
          <Bar :data="chartData" :options="chartOptions" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, useCssModule } from 'vue'
import { useTheme } from '../context/useTheme'
import { products, orders, revenueData } from '../data/mockData'
import { Line, Bar } from 'vue-chartjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend
} from 'chart.js'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend
)

const chartData = computed(() => ({
  labels: revenueData.map(d => d.month),
  datasets: [
    {
      label: 'Revenue',
      data: revenueData.map(d => d.revenue),
      borderColor: '#2563eb',
      backgroundColor: '#2563eb'
    }
  ]
}))

const chartOptions = computed(() => ({
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      labels: {
        color: darkMode.value ? '#e5e7eb' : '#374151'
      }
    }
  },
  scales: {
    x: {
      ticks: { color: darkMode.value ? '#9ca3af' : '#6b7280' }
    },
    y: {
      ticks: { color: darkMode.value ? '#9ca3af' : '#6b7280' }
    }
  }
}))

const styles = useCssModule()
const { darkMode } = useTheme()

const cardBg = computed(() => ({
  backgroundColor: darkMode.value ? '#1f2937' : '#ffffff'
}))

const totalRevenue = orders.reduce((sum, o) => sum + o.total, 0)

const kpis = [
  { label: 'Total Revenue', value: `£${totalRevenue.toFixed(2)}`, icon: '💰', color: '#2563eb' },
  { label: 'Total Orders', value: orders.length, icon: '🛒', color: '#16a34a' },
  { label: 'Total Products', value: products.length, icon: '📦', color: '#9333ea' },
  { label: 'Low Stock Items', value: products.filter(p => p.stock < 50).length, icon: '⚠️', color: '#dc2626' },
]
</script>

<style module src="../css/global.module.css"></style>
